import {categories} from '../categories.js';
import {state} from '../state.js';
import {closeCommentBox} from './closeCommentBox.js';
import {removeAnnotation} from './removeAnnotation.js';
export function openCommentBox(annotation){
  closeCommentBox();
  const wrap=document.querySelector(`.page-wrap[data-page="${annotation.page}"]`);
  const target=document.querySelector(`.highlight[data-id="${CSS.escape(annotation.id)}"]`);
  if(!wrap||!target)return;
  state.openCommentId=annotation.id;
  document.getElementById('viewer')?.classList.add('comments-open');
  const box=document.createElement('aside');
  box.className='comment-box';
  box.dataset.id=annotation.id;
  const targetRect=target.getBoundingClientRect();
  const wrapRect=wrap.getBoundingClientRect();
  box.style.top=`${Math.max(8,targetRect.top-wrapRect.top)}px`;
  const header=document.createElement('div');
  header.className='comment-header';
  const title=document.createElement('strong');
  title.textContent=categories[annotation.category].name;
  const close=document.createElement('button');
  close.className='comment-close';
  close.type='button';
  close.textContent='×';
  close.setAttribute('aria-label','Close comment');
  close.addEventListener('click',closeCommentBox);
  header.append(title,close);
  const textarea=document.createElement('textarea');
  textarea.className='comment-text';
  textarea.placeholder='Add comment…';
  textarea.value=annotation.comment||'';
  textarea.addEventListener('input',()=>{annotation.comment=textarea.value;});
  const actions=document.createElement('div');
  actions.className='comment-actions';
  const deleteButton=document.createElement('button');
  deleteButton.className='comment-delete';
  deleteButton.type='button';
  deleteButton.textContent='Delete highlight';
  deleteButton.addEventListener('click',()=>removeAnnotation(annotation.id));
  actions.append(deleteButton);
  box.append(header,textarea,actions);
  wrap.appendChild(box);
  requestAnimationFrame(()=>textarea.focus({preventScroll:true}));
}